# Generated by Django 4.2.5 on 2023-09-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='student',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student',
            field=models.ManyToManyField(to='student.student'),
        ),
    ]
