# Generated by Django 4.2.5 on 2023-09-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
