# Generated by Django 4.2.5 on 2023-09-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_attendancerecord_is_present'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='is_present',
            new_name='is_absent',
        ),
    ]
