# Generated by Django 4.2.5 on 2023-09-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_attendancerecord_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='is_present',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False')], default='F', max_length=1),
        ),
    ]
