# Generated by Django 4.2.5 on 2023-09-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_is_present_attendancerecord_is_absent'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default='This is desc'),
            preserve_default=False,
        ),
    ]
